### ISSUE TITLE
Swap in header images

### ISSUE THREAD

**Issue by voveson** [voveson/crayons-and-cairns#2]

**Comment by voveson** [comment]
I'm working on the header & nav bar for the mobile version -- I think we need to crop some of the space out of the top of the image for mobile so that you see more of the cairn.  What do you think @ltitensor ?  I also switch to text-only in the nav bar for mobile because it worked better spatially.  We can stick with that, or if you want to create a mobile version of the logo that puts "Crayons & Cairns" side by side vs. stacked, that would also work.

**Comment by ltitensor** [comment]
I'm not sure if I have a huge preference. I probably won't till I see it.
I'll create a different version and we can just see what works.

On Monday, July 13, 2015, Vince Oveson notifications@github.com wrote:

> I'm working on the header & nav bar for the mobile version -- I think we
> need to crop some of the space out of the top of the image for mobile so
> that you see more of the cairn. What do you think @ltitensor
> https://github.com/ltitensor ? I also switch to text-only in the nav
> bar for mobile because it worked better spatially. We can stick with that,
> or if you want to create a mobile version of the logo that puts "Crayons &
> Cairns" side by side vs. stacked, that would also work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/voveson/crayons-and-cairns/issues/2#issuecomment-120991756
> .

## 

Laura Titensor
Titensortraining@gmail.com
