### ISSUE TITLE
Ombre

### ISSUE THREAD

**Issue by ltitensor** [voveson/crayons-and-cairns#4]
So you can hardly tell with the "Ombre" words up top so lets scratch it. Thanks!

**Comment by voveson** [comment]
What color should we go with for the navigation links then? Also, I'm thinking in this font they might need to be bigger -- what do you think?

**Comment by ltitensor** [comment]
I do like just leaving them a grey/black. Match the color in the Logo.
Ya they are a bit hard to see so if we can make them bigger then great!
