### ISSUE TITLE
Social Media Links

### ISSUE THREAD

**Issue by voveson** [voveson/crayons-and-cairns#5]
Currently I have put placeholders in the sidebar for links to facebook, twitter, and instagram.  I found your twitter and instagram pages -- do you have (or plan to have) a facebook page set up?  Do you want links to any other social media sites? (pinterest, youtube, etc.)

**Comment by ltitensor** [comment]
We are going to have a Facebook for sure but don't yet. I think we'll
probably have a youtube but not immediately.

On Tue, Jul 14, 2015 at 5:33 PM, Vince Oveson notifications@github.com
wrote:

> Currently I have put placeholders in the sidebar for links to facebook,
> twitter, and instagram. I found your twitter and instagram pages -- do you
> have (or plan to have) a facebook page set up? Do you want links to any
> other social media sites? (pinterest, youtube, etc.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/voveson/crayons-and-cairns/issues/5.

## 

Laura Titensor
Titensortraining@gmail.com

**Comment by smartash** [comment]
We have a Pinterest. It should be under crayons and cairns

**Comment by voveson** [comment]
I'm not finding your pinterest... I tried:
- https://www.pinterest.com/crayonsandcairns/
- https://www.pinterest.com/crayonsncairns/
- https://www.pinterest.com/crayons&cairns/

Can you post a link to it? @smartash

**Comment by smartash** [comment]
We're @CCadventuremoms. I'll see if I can send a link...

**Comment by smartash** [comment]
Ah, yes. So it's www.pinterest.com/CCadventuremoms/
