### ISSUE TITLE
"Coming Soon" page

### ISSUE THREAD

**Issue by smartash** [voveson/crayons-and-cairns#6]
Since we now have followers on instagram and other social media, I'd like a "coming soon" something to have on our site.  How hard would that be?  It doesn't need to be anything special, I just want the links in our social media to go to something other than the wordpress default whatever.

**Comment by voveson** [comment]
I think that's a good idea.  We can definitely put something up easily.  I'll put something together and let you guys take a look.  I'll need access to your bluehost account in order to deploy it. @smartash

**Comment by voveson** [comment]
I have a "Coming Soon" page up on the beta site now:

http://52.24.122.177/candc-beta/coming-soon/

Let me know if you want something different.  If this is good, let's get it posted on your site.

**Comment by ltitensor** [comment]
It looks really good. How do you get access to bluehost? is this like an
"invite" thing or we give you the login and password?

On Mon, Jul 20, 2015 at 12:30 PM, Vince Oveson notifications@github.com
wrote:

> I have a "Coming Soon" page up on the beta site now:
> 
> http://52.24.122.177/candc-beta/coming-soon/
> 
> Let me know if you want something different. If this is good, let's get it
> posted on your site.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/voveson/crayons-and-cairns/issues/6#issuecomment-122978292
> .

## 

Laura Titensor
Titensortraining@gmail.com

**Comment by smartash** [comment]
I think it looks great! I like that it'll link them to our social media so we can announce there, etc. 
ash

**Comment by voveson** [comment]
@ltitensor I will probably need the username & password for both Bluehost and your wordpress admin.

**Comment by ltitensor** [comment]
crayonsandcairns.com Look@ca1rn

On Mon, Jul 20, 2015 at 1:35 PM, Vince Oveson <notifications@github.com>
wrote:

> @ltitensor <https://github.com/ltitensor> I will probably need the
> username & password for both Bluehost and your wordpress admin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voveson/crayons-and-cairns/issues/6#issuecomment-123000920>
> .
>



-- 
Laura Titensor
Titensortraining@gmail.com

**Comment by voveson** [comment]
Sorry, I should have said not to post it here -- this forum is technically public.  I deleted it immediately.  I copied it down, so I'll try and get the 'Coming Soon' page up right away!

**Comment by voveson** [comment]
The "Coming Soon" page is live.
