### ISSUE TITLE
About page image slider

### ISSUE THREAD

**Issue by voveson** [voveson/crayons-and-cairns#7]
I felt like the "About" page felt kind of static, so I added an image slider.  I won't be offended if you guys don't like it, and I can change it back to the single image you originally gave me.  I just think this gives the page a nice look.

Obviously if you like this, you can choose whatever pics you want for it -- I just stole this off Laura's blog.  Let me know what you guys think! @ltitensor @smartash

**Comment by smartash** [comment]
I like it!  It adds a lot.  I didn't even know that's what I wanted until I saw it.  now I'm like, For sure!!
